// Golden-fixture generator (spec §9): replays scripted scenarios through the
// TESTED JS core and records trajectories. The Swift RewardCore must reproduce
// these within 1e-3. Run: node simulator/tests/gen_fixtures.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, '..', 'index.html'), 'utf8');
const m = html.match(/<script id="nearfield-core">([\s\S]*?)<\/script>/);
const ctx = vm.createContext({ console });
vm.runInContext(m[1], ctx);

const DT = 0.2;
const params = JSON.parse(JSON.stringify(ctx.DEFAULT_PARAMS));
const scale = JSON.parse(JSON.stringify(ctx.DEFAULT_SCALE));

// --- prng: raw sequences to verify the Swift port bit-for-bit-ish ------------
const rng42 = ctx.mulberry32(42);
const prngRaw = Array.from({ length: 16 }, () => rng42());
const g42 = ctx.mulberry32(42);
const gaussianRaw = Array.from({ length: 8 }, () => ctx.gaussian(g42));

// --- pairSensor: recorded noisy RSSI trace -> buckets + encounters -----------
const radio = new ctx.PairRadio(params, ctx.mulberry32(99));
const distanceAt = t => (t < 20 ? 8.0 : t < 50 ? 1.2 : 8.0);
const sensor = new ctx.PairSensor(params);
const pairTrace = [];
for (let i = 0; i < 400; i++) {
  const t = i * DT;
  const rssi = radio.update(DT, distanceAt(t));
  const s = sensor.update(DT, rssi);
  pairTrace.push({ rssi, bucket: s.bucket, encounter: s.encounterActive ? 1 : 0 });
}

// --- fingerprint: seeded OU walk with amplitude ramp --------------------------
const fpSeed = ctx.fnv1a('7|1700000000');
const fp = new ctx.FingerprintDrift(fpSeed, params, 1.0, 300);
const fpTrace = [];
for (let i = 0; i < 600; i++) {
  const t = i * DT;
  const amplitude = t < 60 ? 1 : Math.max(0, 1 - (t - 60) / 20);
  fpTrace.push(fp.update(DT, amplitude));
}

// --- rewardState: the full dance scenario -------------------------------------
const me = { id: 0, role: 'voice', pitchHz: 220 };
const peer2Pitch = 220 * Math.pow(2, 551.2 / 1200);
const reward = new ctx.RewardState(me, params, scale);
const scenario = t => {
  // phases: solo+motion, encounter, parked (habituate), second peer,
  // both leave, gated re-encounter (bloomMultiplier)
  const p1near = (t >= 10 && t < 90) || t >= 120;
  const p1enc = (t >= 12 && t < 92) || t >= 122;
  const p2near = t >= 70 && t < 90;
  const p2enc = t >= 72 && t < 92;
  const motion = t < 40 ? 0.6 : t < 70 ? 0.0 : t < 90 ? 0.5 : 0.2;
  const bloomMultiplier = t >= 120 ? 0.3 : 1.0;
  return {
    encounters: new Map([[1, p1enc], [2, p2enc]]),
    buckets: new Map([[1, p1near ? 'near' : 'far'], [2, p2near ? 'near' : 'far']]),
    motion,
    peerPitches: new Map([[1, 220], [2, peer2Pitch]]),
    bloomMultiplier,
  };
};
const rewardTrace = [];
for (let i = 0; i < 750; i++) {
  const t = i * DT;
  const out = reward.update(DT, scenario(t));
  rewardTrace.push({
    W: out.W, B: out.B, E: out.E, F: out.F,
    novelty: out.novelty,
    focusId: out.focusId === null ? -1 : out.focusId,
    detune: out.detuneCents,
    g2: out.partialGains[1], g3: out.partialGains[2],
  });
}

// --- score: keyframe interpolation, labels, stretch, drift-scale rows ---------
const scoreState = new ctx.ScoreState(ctx.DEFAULT_SCORE, params);
const scoreSamples = [0, 30, 60, 90, 120, 200, 300, 420, 510, 600, 700, 840, 900, 930, 960].map(t => ({
  t,
  label: scoreState.labelAt(t),
  bloom: scoreState.valueAt('bloom_multiplier', t),
  master: scoreState.valueAt('master_multiplier', t),
  fpAmp: scoreState.valueAt('drift.fingerprint_amplitude', t),
  breath: scoreState.valueAt('breath.period_s', t),
  tauAttack: scoreState.valueAt('encounter.tau_attack_s', t) ?? -1,
  novelty: scoreState.valueAt('wind.alpha_novelty_per_s', t) ?? -1,
  stretch: scoreState.stretchAt(t),
}));
const drift = ctx.DEFAULT_SCALE_DRIFT;
const scaleSamples = [2.04, 2.055, 2.07, 2.0851, 2.1].map(s => {
  const r = ctx.interpolateScale(drift, s);
  return { stretch: s, scaleCents: r.scale_cents, dips: r.dip_intervals_cents, ratio2: r.spectrum.ratios[1] };
});

const fixtures = {
  version: 1,
  dt: DT,
  note: 'generated by simulator/tests/gen_fixtures.mjs from the tested JS core; Swift must match within 1e-3',
  prng: { seed: 42, raw: prngRaw, gaussian: gaussianRaw },
  pairSensor: { trace: pairTrace },
  fingerprint: { seedString: '7|1700000000', seed: fpSeed, freqHz: 300, roleMult: 1.0, trace: fpTrace },
  reward: {
    me: { id: 0, role: 'voice', pitchHz: 220 },
    peer2PitchHz: peer2Pitch,
    trace: rewardTrace,
  },
  score: { samples: scoreSamples },
  scaleDrift: { samples: scaleSamples },
};

const outDir = join(here, '..', '..', 'config', 'fixtures');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'reward_golden.json'), JSON.stringify(fixtures) + '\n');
console.log('wrote config/fixtures/reward_golden.json',
  `(pair ${pairTrace.length}, fp ${fpTrace.length}, reward ${rewardTrace.length} ticks)`);
